/*
 * This source file was generated by the Gradle 'init' task
 */
package github.yairm210.`kotlin-ir-explorer`.server

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
}
