/*
 * This file was generated by the Gradle 'init' task.
 */

//plugins {
//    id("buildlogic.kotlin-library-conventions")
//}


dependencies {
    "implementation"("org.jetbrains.kotlin:kotlin-compiler:2.0.0")
}
