/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

dependencies {
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
