/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    // kotlinx serialization
    kotlin("plugin.serialization") version "1.9.0"
    id("com.gradleup.shadow") version "8.3.5"
}

apply(plugin = "kotlinx-serialization")

val ktorVersion = "2.3.4"

dependencies {
    implementation(project(":core"))
    
    // ktor
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-server-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
    implementation("io.ktor:ktor-server-default-headers:$ktorVersion")
    implementation("io.ktor:ktor-server-compression:$ktorVersion")
    implementation("io.ktor:ktor-server-host-common:$ktorVersion")
    implementation("io.ktor:ktor-server-config-yaml:$ktorVersion")
    implementation("ch.qos.logback:logback-classic:1.5.13")
    implementation("io.ktor:ktor-server-cors:$ktorVersion")
    
    
    //testing
    testImplementation("io.ktor:ktor-server-test-host:$ktorVersion")
    // kotlin test
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:2.0.0")
}


application { // for local development
    mainClass = "io.ktor.server.netty.EngineMain"
}

// for production deployment - see https://stackoverflow.com/questions/32567167/gradle-no-main-manifest-attribute
//tasks.withType<Jar> {
//    manifest {
//        attributes["Main-Class"] = "github.yairm210.kotlin_ir_explorer.server.ServerKt"
//    }
//}