/*
 * This source file was generated by the Gradle 'init' task
 */
package github.yairm210.`kotlin-ir-explorer`.server

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
